
(() => {
 const page=document.querySelector(".workspace");if(!page)return;const tool=page.dataset.tool;if(!tool.startsWith("image-"))return;
 const input=document.getElementById("fileInput"),btn=document.getElementById("processBtn"),status=document.getElementById("status"),result=document.getElementById("result"),files=[];
 const render=()=>{const b=document.getElementById("fileList");b.innerHTML=files.map((f,i)=>`<div class="file-item"><span>IMG</span><div class="grow"><strong>${f.name}</strong><small>${Siznora.fmtSize(f.size)}</small></div><button data-i="${i}">Remove</button></div>`).join("");b.querySelectorAll("button").forEach(x=>x.onclick=()=>{files.splice(+x.dataset.i,1);render();btn.disabled=!files.length})};
 input?.addEventListener("change",()=>{files.length=0;for(const f of input.files)if(/^image\/(jpeg|png|webp)$/.test(f.type)&&f.size)files.push(f);render();btn.disabled=!files.length;if(tool==="image-resize"&&files[0])loadDims(files[0])});
 const loadDims=async f=>{const im=await createImageBitmap(f);document.getElementById("dimensions").textContent=`Original dimensions: ${im.width} × ${im.height}`;width.value=im.width;height.value=im.height};
 const canvasBlob=async(f,w,h,type,q)=>{const im=await createImageBitmap(f);const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(im,0,0,w,h);return new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(Error("Could not encode image.")),type,q))};
 const ext=t=>t==="image/jpeg"?".jpg":t==="image/webp"?".webp":".png";
 const zipOut=async outs=>{if(outs.length===1){Siznora.download(outs[0].blob,outs[0].name);return}const JSZip=(await import("https://cdn.jsdelivr.net/npm/jszip@3.10.1/+esm")).default;const z=new JSZip();outs.forEach(o=>z.file(o.name,o.blob));const blob=new Blob([await z.generateAsync({type:"uint8array"})],{type:"application/zip"});Siznora.download(blob,"Siznora_Image_Results.zip");result.hidden=false;result.innerHTML='<h3>✓ Complete</h3><p>Your files were processed locally.</p><a class="download" href="'+URL.createObjectURL(blob)+'" download="Siznora_Image_Results.zip">Download All ZIP</a>'};
 const go=async()=>{status.textContent="Processing locally...";let outs=[];if(tool==="image-resize"){const f=files[0];const im=await createImageBitmap(f);const preset=document.getElementById("preset").value;let w=+width.value,h=+height.value;if(preset!=="custom"){w=Math.max(1,Math.round(im.width*+preset/100));h=Math.max(1,Math.round(im.height*+preset/100));width.value=w;height.value=h}else if(document.getElementById("aspect").checked)h=Math.max(1,Math.round(w*im.height/im.width));const type=document.getElementById("format").value==="auto"?f.type:document.getElementById("format").value;outs.push({blob:await canvasBlob(f,w,h,type,.92),name:"Siznora_Resized"+ext(type)})}else for(const f of files){const im=await createImageBitmap(f);let type=document.getElementById("format").value;if(type==="auto")type=tool==="image-compress"?(f.type==="image/png"?"image/webp":f.type):"image/jpeg";const q=+(document.getElementById("quality")?.value||.9);outs.push({blob:await canvasBlob(f,im.width,im.height,type,q),name:"Siznora_"+f.name.replace(/\.[^.]+$/,"")+ext(type)})}await zipOut(outs);status.textContent="Done."};
 if(btn)btn.onclick=async()=>{btn.disabled=true;try{await go()}catch(e){status.textContent="Unable to process this image. Please check that the file is valid and try again."}finally{btn.disabled=false}};
})();
